### ISSUE TITLE
Edit asset not working

### ISSUE THREAD

**Issue by tmberthold** [sovity/edc-ui#774] opened 2024-07-24 08:50 UTC
**Describe the bug**
When editing an asset, after clicking the update button the asset is not updated and all buttons are greyed out. The user needs to press escape or refresh page to exit the edit dialog.

**To Reproduce**
1. Go to Assets
2. Select an asset and open the details.
3. Click on edit button.
4. Make changes and click update

**Expected behavior**
The asset details are updated, the user is informed about the operation result, the edit window is closed.

**Screenshots**

**MDS Versions (please complete the following information):**
 - EDC: [9.0.0]
 - EDC-UI: [4.0.0]

**Comment by AbdullahMuk** [comment] 2024-07-30 11:02
@illfixit please confirm if the bug is only frontend related.

In case it is NOT only frontend related, please let me know if you need another team member to solve this issue.

**Comment by illfixit** [comment] 2024-08-01 09:58
The issue is reopened since some assets still cannot be updated in mds-open-source-version

**Comment by illfixit** [comment] 2024-08-05 14:56
Fixed in #781

**Closed** 2024-08-05 14:55 UTC
Labels: scope/mds, kind/bug, bug/usability
